# Generated by Django 5.2 on 2025-04-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('site_type', models.CharField(choices=[('whtm', 'Warehouse Total Metering'), ('savings', 'Warehouse Savings'), ('submetering', 'Warehouse Submetering'), ('fems', 'Equipment Management'), ('firemonitor', 'Fire Monitoring System')], default='savings', max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('live_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_factor', models.BooleanField(default=False)),
                ('hourly_data', models.BooleanField(default=False)),
                ('load_data_graph', models.BooleanField(default=False)),
                ('alarm_history', models.BooleanField(default=False)),
                ('carbon_emission', models.BooleanField(default=False)),
                ('fuel_data', models.BooleanField(default=False)),
                ('dg_mains_runtime', models.BooleanField(default=False)),
                ('voltage_alarms', models.BooleanField(default=False)),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.site')),
            ],
        ),
        migrations.CreateModel(
            name='HomeGatewayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_gatewway_id', models.CharField(max_length=50)),
                ('rssh_port', models.IntegerField()),
                ('monitoring_port', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.site')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('live_date', models.DateTimeField()),
                ('source', models.CharField(default='mains', max_length=12)),
                ('shows_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows_on', to='warehouse.site')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='site_manager',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='warehouse.sitemanager'),
        ),
    ]
