# Generated by Django 5.2 on 2025-04-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_site_live_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.sitemanager'),
        ),
    ]
